### ISSUE TITLE
Issue with path with space in it

### ISSUE THREAD

**Issue by nicolaslauquin** [andrewmarmion/bitrise-step-firebase-dsym-upload#1]
Hello, 

there is an issue with dsym upload containing space in the name or path could you surrounded $fdu_dsym_location with ` so it will work in any situation, thank you (I had to force the name and loose some time to make it work, so I think it would be nice to other people having this fix):

The line where the problem resides would be this:  https://github.com/andrewmarmion/bitrise-step-firebase-dsym-upload/blob/506b18c2bcb86454a580fe2b2e6154fa12baa933/step.sh#L18

Thank you!

**Comment by andrewmarmion** [comment]
I’m happy for a PR on this. However, if this issue is affecting the DSYM location it could also affect the location of the plist and fabric/firebase. So they would also need to be updated too.

**Comment by andrewmarmion** [comment]
Closing this issue as version 1.0.1 should fix this.

**Comment by hyde1** [comment]
Hello there, I am reopening this issue as a space in the path would also trigger a shell error on that line:
https://github.com/andrewmarmion/bitrise-step-firebase-dsym-upload/blob/3bf45ea0e02aae0646ad6553bbcffd124df92a52/step.sh#L13
It should be enclosed with quotes as the other `ifs`.
