### ISSUE TITLE
Version 1.1.0 breaks builds setup with version 1.0.2

### ISSUE THREAD

**Issue by nickspragg** [andrewmarmion/bitrise-step-firebase-dsym-upload#10]
In step.yml there was a default value provided for _fdu_fabric_location_ which was removed in version 1.1.0. -> https://github.com/andrewmarmion/bitrise-step-firebase-dsym-upload/commit/2f288800b2f04969f55898e4f9b260d2bbec18e0#diff-91d8d269a1c9bd3631ddb04b80b01c4e

Can you please re-add the default value so that it does not break existing setups where people have not changed the default value.

**Comment by andrewmarmion** [comment]
Fabric is being deprecated in favour of FirebaseCrashlytics. Hence having a default value will cause issues. 

FirebaseCrashlytics has a different location of where `upload-symbols` is stored, hence the default value in 1.0.2 was removed in 1.1.0. 

The description for the location was updated and contains the previous default value which was: 

> For Fabric it is usually `./Pods/Fabric/upload-symbols` and FirebaseCrashlytics it is usually `./Pods/FirebaseCrashlytics/upload-symbols`

To fix your build you can use the default value for Fabric that is provided in the description. However, please note that Fabric is being deprecated shortly and you should move to using FirebaseCrashlytics.

**Comment by nickspragg** [comment]
Thanks Andrew. I am aware that Fabric as a service has been discontinued and that the Fabric Pod is deprecated, but we still have it in use in the our project. I wasn't expecting a Minor version to break the build though, so our version step was not locked to the specific version.

It would make more sense to release a version 2.0.0 which remove the Fabric support completely and retain the existing default value in version 1.1.X where the Fabric Pod is still supported by the build step.

I appreciate your time and effort in developing and maintaining the build step. I wanted to let you know the impact it had.

**Comment by andrewmarmion** [comment]
Fair point, I always lock my steps just incase. I have put 1.1.1 out that will return the default value to Fabric's location. #11 fixes this. Just waiting now on Bitrise to approve the merge.
