### ISSUE TITLE
upload-symbols broken in FirebaseCrashlytics 4.1.1

### ISSUE THREAD

**Issue by andrewmarmion** [andrewmarmion/bitrise-step-firebase-dsym-upload#12]
Currently the upload-symbols script in FirebaseCrashlytics is broken. It returns the following error

    error: Could not fetch upload-symbols settings: An unknown error occurred fetching settings.

This means that it is not currently possible to upload the dsyms to Firebase. 

I have also checked the command locally and it does not work there.

From the [documentation](https://firebase.google.com/docs/crashlytics/get-deobfuscated-reports?platform=ios&authuser=0) we can see the following: 

> Note: upload-symbols is in the process of integrating with the rest of the Firebase CLI tools.

![Screenshot 2020-06-10 at 18 15 27](https://user-images.githubusercontent.com/13627302/84298065-6e9c0300-ab46-11ea-8591-6d529f9caaa2.png)

I have opened an [issue](https://github.com/firebase/firebase-ios-sdk/issues/5787) on the Firebase repo .

**Comment by mdesjardins** [comment]
it'd be cool to add a retry debug option for this? perhaps if I can figure out how to do this I'll submit a PR. :)

**Comment by andrewmarmion** [comment]
I am closing this as it is not replicated in the current versions of Firebase
