### ISSUE TITLE
Suggestion: Change fdu_fabric_location default from Fabric to Firebase

### ISSUE THREAD

**Issue by rickmanelius** [andrewmarmion/bitrise-step-firebase-dsym-upload#13]
Given the deprecation of Fabric in November 2020, a lot of users will need to change their dsyms location. If people are reliant on the default value when they switch their podfile, they will hit this error (which fails, but without an indication why during the build process). Thanks for your amazing work!

**Comment by andrewmarmion** [comment]
Currently the step is commented with both options and there is a warning printed in the log about the change that is coming in November (this warning is printed on run of the step - whether it is successful or not). 

I am intending on releasing version 2 in October that will change the default value from Fabric to Firebase.

**Comment by andrewmarmion** [comment]
I am closing this issue as #14 fixes addresses this issue.
