### ISSUE TITLE
Cannot find Firebase Location if Folder has Spaces

### ISSUE THREAD

**Issue by nmaniatis** [andrewmarmion/bitrise-step-firebase-dsym-upload#17]
Hi, I have realised that my bitrise flow Upload dsyms to Firebase is not working because my path to the Google service plist has spaces. When I paste my path to the workflow thought the editor, it looks like this:
./Project_Name/App_Name/Supporting Files/Google Analytics/GoogleService-info.plist

When I go and see the Bitrise yml it looks like this:
 - firebase-dsym-upload@2:
        is_skippable: true
        inputs:
        - fdu_google_services_location: "./Project_Name/App_Name/Supporting Files/Google
            Analytics/GoogleService-info.plist"

It changes line after Google and I don't know if this is the issue but I wanted to write everything I could. I am pretty sure it has to do something to do with the Supporting Files and Google Analytics folders which they have spaces. In Terminal I would write something like this:

/path_to_project/Project_Name/App_Name/Pods/FirebaseCrashlytics/upload-symbols -gsp /path_to_project/Project_Name/App_Name/Supporting\ Files/Google\ Analytics/GoogleService-Info.plist -p ios Downloads/appDsyms

The backslash indicates the space and it only works with backslash for me in the terminal.

Thanks.

**Comment by andrewmarmion** [comment]
This was a previous issue and was fixed in version 1.0.1. I am unsure how it has raised its head again. As far as I can tell this should not be possible. 

I am open to pull requests if you have a solution.

**Comment by nmaniatis** [comment]
Sorry @andrewmarmion it was a bug on our end, you can delete this issue!

**Comment by andrewmarmion** [comment]
@nmaniatis That is ok. Happy that it is resolved
