### ISSUE TITLE
Step shows successful completion in Bitrise log, but dSYM not uploaded to Firebase.

### ISSUE THREAD

**Issue by smalomo** [andrewmarmion/bitrise-step-firebase-dsym-upload#18]
The Bitrise log shows this step completed successfully and the file was uploaded to Firebase but in Firebase it shows the dSYM is missing for this build. 
<img width="682" alt="bitrise step completed successfully" src="https://user-images.githubusercontent.com/2349287/145128709-b24ebd69-b8ee-49fe-8751-9a913eb07d98.png">
<img width="963" alt="missing dSYM from Firebase Crashlytics" src="https://user-images.githubusercontent.com/2349287/145128874-7c6bc77e-e1f0-4bf2-a905-5aaea6c5b3c9.png">

**Comment by andrewmarmion** [comment]
That is strange. 

This step is just a wrapper around the the `upload-symbols` script provided by Firebase. 

So the output, in white and green, is actually provided by the `upload-symbols` script  and not by the step. 

> *Successfully submitted symbols for architecture arm64 with UUID ....* 
> *Successfully uploaded Crashlytics symbols* 

You can see the code [here](https://github.com/andrewmarmion/bitrise-step-firebase-dsym-upload/blob/master/step.sh) for the step, which doesn't include any of that text, and in the last line it just calls the location of the `upload-symbols` script in the location of your Crashlytics pod.

I know from experience that it can take some time for the dSYMs to show on Firebase, and there were [AWS issues](https://www.theverge.com/2021/12/7/22822332/amazon-server-aws-down-disney-plus-ring-outage) yesterday that was causing problems for the internet (I don't know if that would cause issues with Google's servers but who knows).

Without a reproducible example it is difficult for me to debug this issue.

**Comment by smalomo** [comment]
Thanks, appreciate you taking a look. This build ran on Friday 12/3 so shouldn't be related to the AWS outage. But I just ran the `upload-symbols` script locally and got the same result - script says it ran successfully and uploaded the files, but they still don't show up in Firebase. This is my first time using Crashlytics so I'll keep troubleshooting there but can rule out this workflow step as being the cause of the issue. Thanks again!

**Comment by iqbalmineraltown** [comment]
Hi, I just met with the same problem recently, the log says uploaded but the Crashlytics says missing even after days since upload
I tried to upload dSYM generated by Bitrise manually and the Crashlytics says it's still missing
But if I uploaded dSYM generated from AppStore, the warning disappear within minutes

seems like appstore generated a new dSYM file?

**Comment by andrewmarmion** [comment]
As I said in a comment above that this is just a wrapper around `upload-symbols` so if it is stating that it has uploaded successfully there isn't much I can do. The uploaded successfully messaged come from Firebase's own code. 

The App Store always generates its own dSYMs as it uses app thinning to strip code that is not required for the specific device that is downloading the app. So the dSYMS produced by the App Store may differ from the ones generated by the build step. 

This step doesn't download the App Store dSYMs as that is a much more complicated procedure and requires access to the your Apple account to download the dSYMs from Apple and then re-upload them to Firebase. 

I would try uploading a local build (not from Bitrise) and see if that works, if it doesn't the next step would be to reach out to Firebase Crashlytics as it would appear that there is an issue with there `upload-symbols` code.
