### ISSUE TITLE
Crashlytics file path without podfile

### ISSUE THREAD

**Issue by bilaldurnagolmomentup** [andrewmarmion/bitrise-step-firebase-dsym-upload#19]
I am not using podfile in my project. I am using package dependencies. And I am getting the following error. I'm probably entering the FirebaseCrashlytics file extension incorrectly. How can I enter the file extension correctly?
![Screen Shot 2022-02-21 at 01 16 26](https://user-images.githubusercontent.com/87535021/154866869-72a4f55d-e114-4b54-9b6c-bdaf4e6e8a0f.png)

**Comment by andrewmarmion** [comment]
This step only supports cocoapods 

https://github.com/andrewmarmion/bitrise-step-firebase-dsym-upload/issues/16#issuecomment-949801411
