### ISSUE TITLE
Please provide the location of Fabric or FirebaseCrashlytics

### ISSUE THREAD

**Issue by dorsamet** [andrewmarmion/bitrise-step-firebase-dsym-upload#20]
Code suggests location is not provided, but it is, some more information might be missing.
Any idea why this might happen?

**Comment by andrewmarmion** [comment]
Firstly this step is for CocoaPods if you are using an alternate way of installing Firebase then it will not work. 

If you are using CocoaPods then you need to make sure that you have put the correct location of where your pods are installed as this step uses Firebase's own upload script that is included in part of their CocoaPod

**Comment by dorsamet** [comment]
`./Pods/FirebaseCrashlytics/upload-symbols`
Currently this is the spot. Weird that it does not find it though, right?

**Comment by dorsamet** [comment]
I think I figured it out, seems like the ios directory needs to be referenced as it's a Flutter project.
