### ISSUE TITLE
Please provide the location of your dSYM

### ISSUE THREAD

**Issue by osa8bit** [andrewmarmion/bitrise-step-firebase-dsym-upload#21]
Hey @andrewmarmion 

I am using this step
I can see in the log the app is already successfully generating the dSYM symbols
[MYAPP] Generating MYAPP.app.dSYM

the Location of the bitrise dSYMs is set to $BITRISE_DSYM_PATH

but the step failed with the following logs:

```sh
+------------------------------------------------------------------------------+

| (13) firebase-dsym-upload@2                                                  |
+------------------------------------------------------------------------------+
| id: firebase-dsym-upload                                                     |
| version: 2.0.0                                                               |
| collection: https://github.com/bitrise-io/bitrise-steplib.git                |
| toolkit: bash                                                                |
| time: 2022-04-13T16:00:52Z                                                   |
+------------------------------------------------------------------------------+
|                                                                              |
Fabric is being deprecated November 15 2020.
Make sure you update your dependencies to use FirebaseCrashlytics before then.
Please provide the location of your dSYM
|                                                                              |
+---+---------------------------------------------------------------+----------+
| x | firebase-dsym-upload@2 (exit code: 1)                         | 3.34 sec |
+---+---------------------------------------------------------------+----------+
| Issue tracker: ...com/andrewmarmion/bitrise-step-firebase-dsym-upload/issues |
| Source: https://github.com/andrewmarmion/bitrise-step-firebase-dsym-upload   |
+---+---------------------------------------------------------------+----------+
```

Any idea please?

**Comment by andrewmarmion** [comment]
That error message will only show if you haven't entered a path for your dSYMs.

Are you sure that you are running the step at the appropriate place in the build pipeline?

Has the step previously worked? Are you using it with cocoapods?

The only thing I can think of is that bitrise hasn't populated the variable when the step is being called.

**Comment by osa8bit** [comment]
here is my configuration am I missing something
<img width="906" alt="Screen Shot 2022-04-13 at 21 17 10" src="https://user-images.githubusercontent.com/45035432/163244947-ce091469-f60e-4efe-a27e-380506be5f9a.png">
?

**Comment by andrewmarmion** [comment]
As I said all I can think of is that bitrise had not populated the variable by the time the step is run. 

Had the step worked previously?

**Comment by osa8bit** [comment]
I am using it for the firs time
do you have any idea where does bitwise store the dSYM symbols?

**Comment by andrewmarmion** [comment]
Bitrise should automatically populate the variable `$BITRISE_DSYM_PATH` when you are using the `xcode-archive` step. You can check out the outputs on the step by scrolling to the bottom of it. 

You should also see something similar to the following in your logs: 

```
The dSYM zip path is now available in the Environment Variable: BITRISE_DSYM_PATH (value: /Users/vagrant/deploy/MyAwesomeApp.dSYM.zip)
```

Having that in your logs means that the variable should have been set. 

You can always check by adding a script step to print out the dSYM path, after the `xcode-archive` step so that you can make sure it is being populated. 

If it is not then you probably need to look at your workflow to make sure that value is being generated and if you think it is but it is still not being populated then you may need to speak to Bitrise yourself.

**Comment by osa8bit** [comment]
than you for the clarification
I am closing the issue
