### ISSUE TITLE
Newest version doesn't work with Xcode 11.4 on the newest macOS catalina

### ISSUE THREAD

**Issue by ethan021021** [andrewmarmion/bitrise-step-firebase-dsym-upload#6]
```Error Domain=com.crashlytics.mac.error-domain.process-dsym Code=4 "This version of OSX is not able to perform the necessary dSYM transformations." UserInfo={NSLocalizedFailureReason=This version of OSX is not able to perform the necessary dSYM transformations.}```

Getting this error when running the latest macOS Catalina. I believe we need to update the `upload-dsyms` binary to the latest.

**Comment by andrewmarmion** [comment]
Which version of Fabric do you have in your Podfile/Podfile.lock? 

I have just tried version 1.0.2 of the step, with my test build (which uses  Fabric 1.10.2 ) using Xcode 11.4 and it uploads without an issue.

The step just uses the uploader that is included with Fabric. If it is not working on Xcode 11.4 then the chances are that your version of Fabric needs to be updated.

**Comment by ethan021021** [comment]
Awesome thanks for the quick reply! I'll test further. One more question: my Xcode project is supposed to be generating dsyms that are bitcode encoded but I still have to re upload the dsyms to firebase from App Store connect. Do you know if apple is adding the bitcode encryption on their end? Or will this step upload bitcode encrypted dsym files from the xcodebuild step?

**Comment by andrewmarmion** [comment]
As far as my understanding is that Apple do their own thing with the dSYMs for apps on the App Store, this is why you have to download the dSYMs from them and upload them to Firebase manually. 

If you are wanting to automate the process of downloading the dSYMs from Apple and uploading them to Firebase, I would suggest looking at Fastlane as they are able to do it. 

The scope of this step is limited,  it just uses Fabric's uploader to upload the dSYMs. It doesn't do anything other than that. I mainly use this step for DEV, UAT, or enterprise builds which do not require bitcode to be enabled.
