### ISSUE TITLE
Incompatibility with xcode-archive step

### ISSUE THREAD

**Issue by rickmanelius** [andrewmarmion/bitrise-step-firebase-dsym-upload#8]
I effectively resolved #5 by determining that the issue with our uploads not being recognized was due to a default option on the xcode-archive step. Once you set these two values "no", then the uploads work perfectly.

See https://discuss.bitrise.io/t/download-dsyms-from-app-store-connect-for-testflight-apps-using-bitcode/12565.

**Comment by andrewmarmion** [comment]
This is not an issue, please do not create issues to comment on previously closed issues.
